# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/SOC_LAB/radio_periph_lab/vivado/radio_periph_lab.srcs/sources_1/bd/design_1/ip/design_1_full_radio_0_0/design_1_full_radio_0_0.xci
# IP: The module: 'design_1_full_radio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/SOC_LAB/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_full_radio_0_0/src/dds_compiler_0/dds_compiler_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet

# IP: c:/SOC_LAB/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_full_radio_0_0/src/fir_compiler_1/fir_compiler_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_compiler_1 || ORIG_REF_NAME==fir_compiler_1} -quiet] -quiet

# IP: c:/SOC_LAB/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_full_radio_0_0/src/fir_compiler_0/fir_compiler_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0} -quiet] -quiet

# XDC: c:/SOC_LAB/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_full_radio_0_0/src/fir_compiler_1/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_compiler_1 || ORIG_REF_NAME==fir_compiler_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/SOC_LAB/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_full_radio_0_0/src/fir_compiler_0/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: C:/SOC_LAB/radio_periph_lab/vivado/radio_periph_lab.srcs/sources_1/bd/design_1/ip/design_1_full_radio_0_0/design_1_full_radio_0_0.xci
# IP: The module: 'design_1_full_radio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/SOC_LAB/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_full_radio_0_0/src/dds_compiler_0/dds_compiler_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet

# IP: c:/SOC_LAB/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_full_radio_0_0/src/fir_compiler_1/fir_compiler_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_compiler_1 || ORIG_REF_NAME==fir_compiler_1} -quiet] -quiet

# IP: c:/SOC_LAB/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_full_radio_0_0/src/fir_compiler_0/fir_compiler_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0} -quiet] -quiet

# XDC: c:/SOC_LAB/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_full_radio_0_0/src/fir_compiler_1/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_compiler_1 || ORIG_REF_NAME==fir_compiler_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/SOC_LAB/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_full_radio_0_0/src/fir_compiler_0/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
